services:
  db:
    image: postgres:15
    container_name: employer-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: employer-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL_EMPLOYER: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5400:5000"
    command: ["python", "app.py"]

volumes:
  postgres_data: