services:
  compliance-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compliance-service
    ports:
      - "5600:5600"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - freelance-network

networks:
  freelance-network:
    driver: bridge