version: "3.9"

services:
  # gighub-db:
  #   image: mysql:8.0
  #   container_name: gighub-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: gighub
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   networks:
  #     - gighub-network

  flask-compliance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-compliance
    ports:
      - "5600:5600"
    env_file:
      - .env
    networks:
      - gighub-network
    restart: always

networks:
  gighub-network:
    external: true  # <--- this is the key
