services:
  escrow-service:
    build: .
    ports:
      - "5200:5000"
    environment:
      - DATABASE_URL=postgresql://escrow_user:escrow_pass@db:5432/escrow_db
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=escrow_user
      - POSTGRES_PASSWORD=escrow_pass
      - POSTGRES_DB=escrow_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
