version: '3.8'

services:
  wallet-api:
    build: .
    ports:
      - "5300:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/wallet_service
      - FLASK_ENV=development
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - wallet-network

  postgres:
    image: postgres:13
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres-data: