version: '3.8'

services:
  accept-job-service:
    build: .
    container_name: accept-job-container
    ports:
      - "6000:5000"  # Map container port 6000 to host port 6000
    environment:
      FLASK_ENV: production  # Set Flask environment to production
      PYTHONUNBUFFERED: 1    # Ensure unbuffered output for logs
