version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs_db
    expose:
      - "5432"

  pendingapproval:
    build: .
    container_name: pendingapproval
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/jobs_db
    ports:
      - "5500:5000"
